export const airports = [
    'Select an airport',
    'Aberdeen Airport',
    'Abu Dhabi International Airport',
    'Adelaide Airport',
    'Aeroporto de Lisboa',
    'Aeroporto de Porto',
    'Aeroporto de São Paulo-Guarulhos',
    'Aeroporto Galeão',
    'Aeroporto Internacional de Belo Horizonte',
    'Aeroporto Internacional de Brasília',
    'Aeroporto Internacional de Fortaleza',
    'Aeroporto Internacional de Guarulhos',
    'Aeroporto Internacional de Manaus',
    'Aeroporto Internacional de Recife',
    'Aeroporto Internacional de Salvador',
    'Aeroporto Internacional de São Paulo',
    'Aeroporto Internacional de Viracopos',
    'Aeroporto Internacional de Vitória',
    'Aeroporto Internacional de Vitória da Conquista',
    'Aeroporto Internacional de Vitória do Espírito Santo',
    'Aeroporto Internacional de Vitória do Rio Grande',
    'Aeroporto Internacional de Vitória do Xingu',
    'Birmingham Airport',
    'Bristol Airport',
    'Bucharest Henri Coanda International Airport',
    'Budapest Ferenc Liszt International Airport',
    'Buenos Aires Ministro Pistarini International Airport',
    'Cairo International Airport',
    'Cape Town International Airport',
    'Charles de Gaulle Airport',
    'Dublin Airport',
    'Dubrovnik Airport',
    'Edinburgh Airport',
    'Frankfurt Airport',
    'Gatwick Airport',
    'Glasgow Airport',
    'Graz Airport',
    'Heathrow Airport',
    'Helsinki Airport',
    'Hong Kong International Airport',
];
